language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
services:
  - mongodb
branches:
  only:
    - master
# before_install:
#   - "npm install -g istanbul"
script:
  - "npm run test-ci"
after_script:
  - "npm install -g coveralls"
  - "cat ./coverage/lcov.info | coveralls"
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info