environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"
services:
  - mongodb
branches:
  only:
    - master
install:
  - "npm install -g istanbul"
  - "npm install"
build: off
test_script:
  - "npm run test-ci"
version: "{build}"